#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=10:00:00
#PBS -l vmem=20gb

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report

# Run the actual python code
singularity exec docker://brainlife/mne:1.2.1 python3 main.py
