#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l walltime=02:00:00
#PBS -N MEEG_filter
#SBATCH --mem=20G

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Run the actual python code
singularity exec docker://aunnikri642/app-freesurfer-mne-source-recon python3 main.py
